[vaults.chatbot]
type = "age"

[secrets.chatbot]
DISCORD_TOKEN = "ENC[6pc8BrhLLP2h0NQai+1U7j+E9kqXm5RhQKOLjXKz5PIgEWsLkvgfZpwW13tlD33z5u9+H1ERpdNCQj1t/WWt4x6ystHySIKzbYql1wjlxP/MXaPsLMAk00Z/JM32xbYBDPJQ8w==]"
SLACK_BOT_TOKEN = "ENC[R7zqzTQAWl728odgieLgISSIL6f/YDmLKdvaBk1lQT6BrqAhcqF/eMu/NwjCPSdkOLwbn980+i8in+12KKcWQHIFCNm62zEEYjf9LrMYxVXTiD5S]"
SLACK_SIGNING_SECRET = "ENC[JTvU4he1027qxHme7VFG9zJRCgpgMDpDDIYqXxLudGr6iFmeHJQhqy04DZIyFKycp57zojMLQxFs8jGa]"
