[vaults.global]
type = "age"

[vaults.tunnel]
type = "age"

[secrets.global]
AKASH_WALLET = "ENC[JBzfRSGyBaIq1twgebjHUPmHgzPBpydfI+OqQoVQvICSp1Uw9mKhuPRwc7a8XW6JxRIv2BMGEkPEc8P0piQTRT/d3XwwOKvVivoF1tyejoXOVLepYEY94L6kv2XFqysbWiqmY4zM]"

[secrets.tunnel]
KADI_TUNNEL_TOKEN = "ENC[bpWh2C5nqBqknhzww25rVbsCw2zNc2dlwhEpmng+AyUiJ5R7vVECVKFDfV8OMsyaSrxqh8R/NUWQ62SAWgqkocLmC0g=]"
