[vaults.global]
type = "age"

[secrets.global]
AKASH_WALLET = "ENC[JBzfRSGyBaIq1twgebjHUPmHgzPBpydfI+OqQoVQvICSp1Uw9mKhuPRwc7a8XW6JxRIv2BMGEkPEc8P0piQTRT/d3XwwOKvVivoF1tyejoXOVLepYEY94L6kv2XFqysbWiqmY4zM]"
KADI_TUNNEL_TOKEN = "ENC[0qWMEGG5UUuIR0rcH3V9WXvpZ80MP4DTp7YUJOZHZh6/SAgq7otpBJD21vDsnjRxLV65OcAGx/nFNxzPFOFz8XQoSBY=]"
