[vaults.model-manager]
type = "age"

[vaults.global]
type = "age"

[secrets.model-manager]
MODEL_MANAGER_BASE_URL = "ENC[RbAr3SPvvtGtzA1KkiVgbOUxV7vcf2nvAgUdo6OP4zA96U2n7sP1BkADwHJefQH8mR/SlF2xT2VHLvHZ0jrzn8t4Yca+oBO9HcF+pt4R/Oq6o+6BgUZi9Ha3]"
MODEL_MANAGER_API_KEY = "ENC[ebvjTp8x9lB+v5poxjnxavktSE/QT6CDHkDq5CuJSLv6pRR/3bLWR+ZuOwCiLq79NqUedrERWCdoOSHtvBcPrfOzSFAx0IC9d3LO7JTDMYNqhQ==]"
ANTHROPIC_API_KEY = "ENC[VTe967umUXRWsUDVbxgonH6JuYRaoBsdEiQzRu/zUKGdgHU05qRNoqG3OS9vubvE2kcQ1Ig6MnewH+uuMq7DtnYCmO0mJeKZG7wPVrCUko5PslHSLuUAgUn8gM4W1l6qEoqgm4I5fEIag9y+8ETzKZWvEt+b8JRlnCPY1Py1E3dvS0Obd/cP4Q==]"

[secrets.global]
AKASH_WALLET = "ENC[JBzfRSGyBaIq1twgebjHUPmHgzPBpydfI+OqQoVQvICSp1Uw9mKhuPRwc7a8XW6JxRIv2BMGEkPEc8P0piQTRT/d3XwwOKvVivoF1tyejoXOVLepYEY94L6kv2XFqysbWiqmY4zM]"
KADI_TUNNEL_TOKEN = "ENC[0qWMEGG5UUuIR0rcH3V9WXvpZ80MP4DTp7YUJOZHZh6/SAgq7otpBJD21vDsnjRxLV65OcAGx/nFNxzPFOFz8XQoSBY=]"
