[vaults.models]
type = "age"

[secrets.models]
MEMORY_API_URL = "ENC[/om3tFD79xGntSAK+vh1vMoy2SUNInukK2g00qFkdHdkFZiMg/g8dRnx4P0QKkCcssdwXIkDkVT1sm8nKgo02Q47FTH4OgPDE+ChAp9NCMFLraNQZ6azlyPB]"
MEMORY_API_KEY = "ENC[6fexlqrV6jBc1snecuk1jGusm4Sjm9t7NPMJx6TtHNCTsCIoOmMjbk8BfKbbuGSP9oJe+DSCYr7dCO4MqIEe8GUeyxPfHWGWPoaULdP3j26l/g==]"
