[vaults.arcadedb]
type = "age"

[vaults.tunnel]
type = "age"

[secrets.arcadedb]
ARCADE_USERNAME = "ENC[JuDWPG/M0H1igvHB7QtkCfRXLLmPCHgGDgKpBrUIaz8=]"
ARCADE_PASSWORD = "ENC[tcOKn1ku97IjdEHrehjWJsUoPEuVOB7R1hmW1rHNlEz5hGHH]"
KADI_TUNNEL_TOKEN = "ENC[89uMWQ921Yh5pAfjqtnNGGzSLo06HnZNh4Hs23S2Pk1LP67MAYiqZA/oeMFYAqvDe9MkC0aQIG7V1gIJIsBdUhqn5Zg=]"

[secrets.tunnel]
KADI_TUNNEL_TOKEN = "ENC[kougiJgNE+1s66FjxkW8OKhqY1wjyMZ7fxGOB8VBmTgBHLWtMFBLnUlo08szTdujAzcjbCMZCMsGx5zcsJBZb0y6lQE=]"
