const ERROR_CODES = {
  // Configuration errors
  INVALID_CONFIG: 'INVALID_CONFIG',
  MISSING_REQUIRED_OPTION: 'MISSING_REQUIRED_OPTION',
  INVALID_PORT: 'INVALID_PORT',
  INVALID_TUNNEL_SERVICE: 'INVALID_TUNNEL_SERVICE',
  INVALID_TIMEOUT: 'INVALID_TIMEOUT',
  
  // Container errors
  CONTAINER_NOT_FOUND: 'CONTAINER_NOT_FOUND',
  CONTAINER_EXPORT_FAILED: 'CONTAINER_EXPORT_FAILED',
  DUPLICATE_CONTAINER: 'DUPLICATE_CONTAINER',
  INVALID_CONTAINER_SPEC: 'INVALID_CONTAINER_SPEC',
  
  // Server errors
  SERVER_START_FAILED: 'SERVER_START_FAILED',
  PORT_IN_USE: 'PORT_IN_USE',
  SERVER_NOT_RUNNING: 'SERVER_NOT_RUNNING',
  
  // Tunnel errors
  TUNNEL_FAILED: 'TUNNEL_FAILED',
  TUNNEL_NOT_AVAILABLE: 'TUNNEL_NOT_AVAILABLE',
  TUNNEL_SERVICE_UNAVAILABLE: 'TUNNEL_SERVICE_UNAVAILABLE',
  TUNNEL_CONNECTION_FAILED: 'TUNNEL_CONNECTION_FAILED',
  TUNNEL_TIMEOUT: 'TUNNEL_TIMEOUT',
  TUNNEL_AUTHENTICATION_FAILED: 'TUNNEL_AUTHENTICATION_FAILED',
  TUNNEL_SERVICE_ERROR: 'TUNNEL_SERVICE_ERROR',
  TUNNEL_HEALTH_CHECK_FAILED: 'TUNNEL_HEALTH_CHECK_FAILED',
  TUNNEL_RECONNECT_FAILED: 'TUNNEL_RECONNECT_FAILED',
  TUNNEL_URL_INVALID: 'TUNNEL_URL_INVALID',
  
  // Authentication errors
  CREDENTIAL_GENERATION_FAILED: 'CREDENTIAL_GENERATION_FAILED',
  CREDENTIALS_EXPIRED: 'CREDENTIALS_EXPIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  
  // File system errors
  EXPORT_DIRECTORY_FAILED: 'EXPORT_DIRECTORY_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  
  // Network errors
  DOWNLOAD_FAILED: 'DOWNLOAD_FAILED',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  
  // Engine errors
  ENGINE_NOT_AVAILABLE: 'ENGINE_NOT_AVAILABLE',
  ENGINE_COMMAND_FAILED: 'ENGINE_COMMAND_FAILED',
  ENGINE_DETECTION_FAILED: 'ENGINE_DETECTION_FAILED',
  DOCKER_NOT_FOUND: 'DOCKER_NOT_FOUND',
  PODMAN_NOT_FOUND: 'PODMAN_NOT_FOUND',
  ENGINE_VERSION_FAILED: 'ENGINE_VERSION_FAILED',
  
  // Container specification errors
  INVALID_CONTAINER_TYPE: 'INVALID_CONTAINER_TYPE',
  CONTAINER_SPEC_MISSING_FIELD: 'CONTAINER_SPEC_MISSING_FIELD',
  CONTAINER_NAME_INVALID: 'CONTAINER_NAME_INVALID',
  CONTAINER_NAME_COLLISION: 'CONTAINER_NAME_COLLISION',
  
  // Phase 1 specific
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  
  // Phase 3 specific - Container Export & OCI Compliance
  TAR_EXTRACTION_FAILED: 'TAR_EXTRACTION_FAILED',
  DIGEST_CALCULATION_FAILED: 'DIGEST_CALCULATION_FAILED',
  OCI_VALIDATION_FAILED: 'OCI_VALIDATION_FAILED',
  MOCK_CONTAINER_CREATION_FAILED: 'MOCK_CONTAINER_CREATION_FAILED',
  TAR_FILE_INVALID: 'TAR_FILE_INVALID',
  MANIFEST_CREATION_FAILED: 'MANIFEST_CREATION_FAILED',
  LAYER_PROCESSING_FAILED: 'LAYER_PROCESSING_FAILED',
  EXPORT_PATH_CREATION_FAILED: 'EXPORT_PATH_CREATION_FAILED',
  CONTAINER_CLEANUP_FAILED: 'CONTAINER_CLEANUP_FAILED',
  
  // Phase 4 specific - S3 Server Integration & Registry API
  REGISTRY_ALREADY_RUNNING: 'REGISTRY_ALREADY_RUNNING',
  SERVER_STOP_FAILED: 'SERVER_STOP_FAILED',
  CREDENTIALS_NOT_AVAILABLE: 'CREDENTIALS_NOT_AVAILABLE',
  S3_SERVER_INIT_FAILED: 'S3_SERVER_INIT_FAILED',
  REGISTRY_WRAPPER_FAILED: 'REGISTRY_WRAPPER_FAILED',
  BUCKET_MAPPING_FAILED: 'BUCKET_MAPPING_FAILED',
  REGISTRY_NOT_RUNNING: 'REGISTRY_NOT_RUNNING',
  REGISTRY_API_ERROR: 'REGISTRY_API_ERROR',
  
  // Phase 6 specific - Advanced Container Management & Monitoring
  INVALID_CONTAINER_ID: 'INVALID_CONTAINER_ID',
  CONTAINER_REMOVAL_FAILED: 'CONTAINER_REMOVAL_FAILED',
  BATCH_OPERATION_FAILED: 'BATCH_OPERATION_FAILED',
  DISCOVERY_FAILED: 'DISCOVERY_FAILED',
  STATISTICS_UNAVAILABLE: 'STATISTICS_UNAVAILABLE',
  MONITORING_FAILED: 'MONITORING_FAILED'
};

export { ERROR_CODES };